My Logger with currying
CodelyTV/scala-intro-examples pull request #1
Opened 2017-12-17 14:34 UTC by joan-miralles

Me faltaría transformarlo en una clase pero todavía no tengo claros algunos conceptos. :books:

2017-12-18 16:15 UTC, JavierCane requested changes
En este caso estaríamos haciendo uso de la encapsulación en funciones para delegar cómo tratar cada uno de los niveles de log.

No obstante, lo que se pide en el ejercicio es hacer esta misma encapsulación gracias al currying. Es decir, invocar parcialmente a la función definida aquí como `log`.

Algo tal que:
```scala
def log(level: String)(message: String): Unit = println(s"[$level] $message")

def debug(message: String): Unit = log(level = "DEBUG")(message)

debug("👋👋👋") // output: "[DEBUG] 👋👋👋"
```

2017-12-18 16:15 UTC, JavierCane commented on src/main/tv/codely/scala_intro_examples/lesson_06_anon_fn_currying/logger.sc
> +def debug = (message: String) => my_log("[DEBUG]", message)
Posible alternativa a la hora de declarar esta misma función:

```scala
def debug(message: String): Unit = my_log("[DEBUG]", message)
```

2017-12-18 16:15 UTC, JavierCane commented on src/main/tv/codely/scala_intro_examples/lesson_06_anon_fn_currying/logger.sc
> +def my_log(level: String, message: String): Unit = log("MISOLUCION")(level, message)
la convención a la hora de definir funciones y valores en Scala es `camelCase`

2017-12-18 16:16 UTC, JavierCane commented on src/main/tv/codely/scala_intro_examples/lesson_06_anon_fn_currying/logger.sc
> +def log(prefix: String)(level: String, value: String): Unit = println("[" + prefix + "]" + level + value)
gracias a especificar el "interpolador" `s` antes de las comillas podemos añadir variables a la hora de formar strings:

antes:
```scala
"[" + prefix + "]" + level + value
```

después:
```scala
s"[$prefix] $level $value"
```

2017-12-18 16:17 UTC, JavierCane commented on src/main/tv/codely/scala_intro_examples/lesson_06_anon_fn_currying/logger.sc
> +//Logger
te agradeceríamos que añadieras tu solución dentro de una nueva subcarpeta `src/main/tv/codely/scala_intro_examples/lesson_06_anon_fn_currying/exercise_solutions/` y con nombre `juan_miralles_logger.sc`. De esta forma otros usuarios también pueden añadir sus propuestas, y podemos mergear la PR :)

Gracias!

2017-12-24 11:20 UTC, joan-miralles commented
Changes done

2018-01-11 21:32 UTC, merged

2018-01-11 21:32 UTC, rgomezcasas commented
Thansk! :)